---
title: "Gwecke test for consistency of Gibbs sampler"
author: "Kieran Campbell"
date: "16 November 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

library(tidyverse)
library(Rcpp)

source("../gibbs/phenotime.R")
sourceCpp("../gibbs/phenotime.cpp")
source("../gibbs/gwecke.R")

set.seed(123L)

scale_vec <- function(x) (x - mean(x)) / sd(x)
```

Make some synthetic x and an initial y:

```{r synthetic}
N <- 50
G <- 10
P <- 2

x <- matrix(sample(0:1, size = N * P, replace = TRUE), ncol = P)

```

Specify initial parameter values:

```{r init-vals}
## precision parameters
tau <- rep(1, G)

## pseudotime parameters
pst <-  rnorm(N)

## parameter initialisation
alpha <- matrix(0, nrow = P, ncol = G)
beta <- matrix(0, nrow = P, ncol = G)
c <- rep(0, G)
eta <- rep(0, G)

tau_pg <- matrix(rgamma(P * G, a_beta, b_beta), nrow = P, ncol  = G)
```

Gwecke test:

```{r gwecke-test}
n_samples <- 1000

## Forward samples
fs_get_dim <- forward_sample(x, G)
fs_df <- data.frame(matrix(NA, nrow = n_samples, ncol = length(fs_get_dim)))
names(fs_df) <- names(fs_get_dim)

for(i in 1:n_samples)
  fs_df[i,] <- unlist(forward_sample(x,G))

gs_df <- data.frame(matrix(NA, nrow = n_samples, ncol = length(fs_get_dim)))
names(gs_df) <- names(fs_get_dim)

pars <- list(
  alpha = alpha, beta = beta, 
  c = c, pst = pst, 
  tau = tau, tau_pg = tau_pg,
  eta = eta
)

for(ns in seq_len(n_samples)) {
  gstep <- gibbs_step(y, x, pars$pst, pars$c, pars$eta, 
                        pars$alpha, pars$beta, pars$tau, pars$tau_pg)
  pars <- gstep$pars
  par_means <- sapply(pars, mean)
  gs_df[ns,] <- c(mean(gstep$y), par_means)
}
```

And plot results:

```{r plot-results}
par(mfrow = c(2,4))
for(variable in names(gs_df)) {
  qqplot(fs_df[[variable]], gs_df[[variable]])
  title(variable)
}
```

